create table if not exists public.app_users (
  email text primary key,
  display_name text not null,
  role text not null check (role in ('viewer', 'editor', 'admin')),
  created_at timestamptz not null default now()
);

create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role
  from public.app_users
  where lower(email) = lower(auth.jwt() ->> 'email')
  limit 1
$$;

create table if not exists public.shows (
  id text primary key,
  play text not null,
  date_seen date,
  book text,
  music text,
  lyrics text,
  adapted_by text,
  director text,
  theatre text,
  run_start date,
  run_end date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cast_members (
  id bigint generated by default as identity primary key,
  show_id text not null references public.shows(id) on delete cascade,
  billing_order integer not null,
  character text,
  actor text
);

create index if not exists cast_members_show_id_idx on public.cast_members(show_id);
create index if not exists cast_members_actor_idx on public.cast_members(actor);

create table if not exists public.show_attendees (
  show_id text not null references public.shows(id) on delete cascade,
  attendee text not null,
  primary key (show_id, attendee)
);

alter table public.app_users enable row level security;
alter table public.shows enable row level security;
alter table public.cast_members enable row level security;
alter table public.show_attendees enable row level security;

drop policy if exists "allowed users can read app users" on public.app_users;
create policy "allowed users can read app users"
on public.app_users for select
to authenticated
using (public.current_app_role() is not null);

drop policy if exists "admins manage app users" on public.app_users;
create policy "admins manage app users"
on public.app_users for all
to authenticated
using (public.current_app_role() = 'admin')
with check (public.current_app_role() = 'admin');

drop policy if exists "allowed users can read shows" on public.shows;
create policy "allowed users can read shows"
on public.shows for select
to authenticated
using (public.current_app_role() is not null);

drop policy if exists "editors can insert shows" on public.shows;
create policy "editors can insert shows"
on public.shows for insert
to authenticated
with check (public.current_app_role() in ('editor', 'admin'));

drop policy if exists "editors can update shows" on public.shows;
create policy "editors can update shows"
on public.shows for update
to authenticated
using (public.current_app_role() in ('editor', 'admin'))
with check (public.current_app_role() in ('editor', 'admin'));

drop policy if exists "editors can delete shows" on public.shows;
create policy "editors can delete shows"
on public.shows for delete
to authenticated
using (public.current_app_role() in ('editor', 'admin'));

drop policy if exists "allowed users can read cast" on public.cast_members;
create policy "allowed users can read cast"
on public.cast_members for select
to authenticated
using (public.current_app_role() is not null);

drop policy if exists "editors can insert cast" on public.cast_members;
create policy "editors can insert cast"
on public.cast_members for insert
to authenticated
with check (public.current_app_role() in ('editor', 'admin'));

drop policy if exists "editors can update cast" on public.cast_members;
create policy "editors can update cast"
on public.cast_members for update
to authenticated
using (public.current_app_role() in ('editor', 'admin'))
with check (public.current_app_role() in ('editor', 'admin'));

drop policy if exists "editors can delete cast" on public.cast_members;
create policy "editors can delete cast"
on public.cast_members for delete
to authenticated
using (public.current_app_role() in ('editor', 'admin'));

drop policy if exists "allowed users can read attendees" on public.show_attendees;
create policy "allowed users can read attendees"
on public.show_attendees for select
to authenticated
using (public.current_app_role() is not null);

drop policy if exists "editors can insert attendees" on public.show_attendees;
create policy "editors can insert attendees"
on public.show_attendees for insert
to authenticated
with check (public.current_app_role() in ('editor', 'admin'));

drop policy if exists "editors can update attendees" on public.show_attendees;
create policy "editors can update attendees"
on public.show_attendees for update
to authenticated
using (public.current_app_role() in ('editor', 'admin'))
with check (public.current_app_role() in ('editor', 'admin'));

drop policy if exists "editors can delete attendees" on public.show_attendees;
create policy "editors can delete attendees"
on public.show_attendees for delete
to authenticated
using (public.current_app_role() in ('editor', 'admin'));

insert into public.app_users (email, display_name, role)
values
  ('amiknox@protonmail.com', 'Andrew', 'admin'),
  ('tina.isaacsknox@gmail.com', 'Tina', 'editor')
on conflict (email) do update
set display_name = excluded.display_name,
    role = excluded.role;
